set(_CATKIN_CURRENT_PACKAGE "image_preproc_ros_tool")
set(image_preproc_ros_tool_VERSION "0.0.0")
set(image_preproc_ros_tool_MAINTAINER "Eike Rehder <eike.rehder@kit.edu>")
set(image_preproc_ros_tool_PACKAGE_FORMAT "2")
set(image_preproc_ros_tool_BUILD_DEPENDS "mrt_cmake_modules" "message_generation" "roscpp" "dynamic_reconfigure" "rosinterface_handler" "roslib" "nodelet" "mrt_opencv" "mrt_cv_bridge_ros" "image_preproc" "image_transport" "utils_ros" "pcl_ros" "pcl_conversions" "mrt_image_geometry_ros" "message_filters")
set(image_preproc_ros_tool_BUILD_EXPORT_DEPENDS "dynamic_reconfigure" "rosinterface_handler" "roslib" "nodelet" "mrt_opencv" "mrt_cv_bridge_ros" "image_preproc" "image_transport" "utils_ros" "pcl_ros" "pcl_conversions" "mrt_image_geometry_ros" "message_filters")
set(image_preproc_ros_tool_BUILDTOOL_DEPENDS "catkin")
set(image_preproc_ros_tool_BUILDTOOL_EXPORT_DEPENDS )
set(image_preproc_ros_tool_EXEC_DEPENDS "message_runtime" "dynamic_reconfigure" "rosinterface_handler" "roslib" "nodelet" "mrt_opencv" "mrt_cv_bridge_ros" "image_preproc" "image_transport" "utils_ros" "pcl_ros" "pcl_conversions" "mrt_image_geometry_ros" "message_filters")
set(image_preproc_ros_tool_RUN_DEPENDS "message_runtime" "dynamic_reconfigure" "rosinterface_handler" "roslib" "nodelet" "mrt_opencv" "mrt_cv_bridge_ros" "image_preproc" "image_transport" "utils_ros" "pcl_ros" "pcl_conversions" "mrt_image_geometry_ros" "message_filters")
set(image_preproc_ros_tool_TEST_DEPENDS "gtest" "rostest")
set(image_preproc_ros_tool_DOC_DEPENDS )
set(image_preproc_ros_tool_URL_WEBSITE "")
set(image_preproc_ros_tool_URL_BUGTRACKER "")
set(image_preproc_ros_tool_URL_REPOSITORY "https://gitlab.mrt.uni-karlsruhe.de/MRT/image_preproc_ros_tool.git")
set(image_preproc_ros_tool_DEPRECATED "")