# CMake generated Testfile for 
# Source directory: /home/kal5-1/cargogo/src/lateral_control_ros_tool
# Build directory: /home/kal5-1/cargogo/build_debug/lateral_control_ros_tool
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(_ctest_lateral_control_ros_tool_gtest_test_discrete_curvature "/home/kal5-1/cargogo/build_debug/lateral_control_ros_tool/catkin_generated/env_cached.sh" "/opt/mrtsoftware/release/lib/mrt-build-tools/bin/python" "/opt/ros/kinetic/share/catkin/cmake/test/run_tests.py" "/home/kal5-1/cargogo/build_debug/lateral_control_ros_tool/test_results/lateral_control_ros_tool/gtest-test_discrete_curvature.xml" "--return-code" "/home/kal5-1/cargogo/devel_debug/.private/lateral_control_ros_tool/lib/lateral_control_ros_tool/test_discrete_curvature --gtest_output=xml:/home/kal5-1/cargogo/build_debug/lateral_control_ros_tool/test_results/lateral_control_ros_tool/gtest-test_discrete_curvature.xml")
add_test(_ctest_lateral_control_ros_tool_rostest_test_lateral_controller_nodelet.test "/home/kal5-1/cargogo/build_debug/lateral_control_ros_tool/catkin_generated/env_cached.sh" "/opt/mrtsoftware/release/lib/mrt-build-tools/bin/python" "/opt/ros/kinetic/share/catkin/cmake/test/run_tests.py" "/home/kal5-1/cargogo/build_debug/lateral_control_ros_tool/test_results/lateral_control_ros_tool/rostest-test_lateral_controller_nodelet.xml" "--return-code" "/opt/ros/kinetic/share/rostest/cmake/../../../bin/rostest --pkgdir=/home/kal5-1/cargogo/src/lateral_control_ros_tool --package=lateral_control_ros_tool --results-filename test_lateral_controller_nodelet.xml --results-base-dir \"/home/kal5-1/cargogo/build_debug/lateral_control_ros_tool/test_results\" /home/kal5-1/cargogo/src/lateral_control_ros_tool/test/lateral_controller_nodelet.test ")
add_test(_ctest_lateral_control_ros_tool_rostest_test_lateral_controller_node.test "/home/kal5-1/cargogo/build_debug/lateral_control_ros_tool/catkin_generated/env_cached.sh" "/opt/mrtsoftware/release/lib/mrt-build-tools/bin/python" "/opt/ros/kinetic/share/catkin/cmake/test/run_tests.py" "/home/kal5-1/cargogo/build_debug/lateral_control_ros_tool/test_results/lateral_control_ros_tool/rostest-test_lateral_controller_node.xml" "--return-code" "/opt/ros/kinetic/share/rostest/cmake/../../../bin/rostest --pkgdir=/home/kal5-1/cargogo/src/lateral_control_ros_tool --package=lateral_control_ros_tool --results-filename test_lateral_controller_node.xml --results-base-dir \"/home/kal5-1/cargogo/build_debug/lateral_control_ros_tool/test_results\" /home/kal5-1/cargogo/src/lateral_control_ros_tool/test/lateral_controller_node.test ")
add_test(_ctest_lateral_control_ros_tool_nosetests_test "/home/kal5-1/cargogo/build_debug/lateral_control_ros_tool/catkin_generated/env_cached.sh" "/opt/mrtsoftware/release/lib/mrt-build-tools/bin/python" "/opt/ros/kinetic/share/catkin/cmake/test/run_tests.py" "/home/kal5-1/cargogo/build_debug/lateral_control_ros_tool/test_results/lateral_control_ros_tool/nosetests-test.xml" "--return-code" "/usr/bin/cmake -E make_directory /home/kal5-1/cargogo/build_debug/lateral_control_ros_tool/test_results/lateral_control_ros_tool" "/usr/bin/nosetests-2.7 -P --process-timeout=60 --where=/home/kal5-1/cargogo/src/lateral_control_ros_tool/test --with-xunit --xunit-file=/home/kal5-1/cargogo/build_debug/lateral_control_ros_tool/test_results/lateral_control_ros_tool/nosetests-test.xml")
subdirs(gtest)
