set(_CATKIN_CURRENT_PACKAGE "kal")
set(kal_VERSION "1.0.0")
set(kal_MAINTAINER "Sascha Wirges <sascha.wirges@kit.edu>")
set(kal_PACKAGE_FORMAT "2")
set(kal_BUILD_DEPENDS "mrt_cmake_modules" "demo_image_processing_ros_tool" "joy_converter_ros_tool" "lateral_control_ros_tool" "longitudinal_control_ros_tool" "motor_interface_ros_tool" "path_provider_ros_tool" "simulation_ros_tool" "tui_ros_tool" "vehicle_setup")
set(kal_BUILD_EXPORT_DEPENDS "demo_image_processing_ros_tool" "joy_converter_ros_tool" "lateral_control_ros_tool" "longitudinal_control_ros_tool" "motor_interface_ros_tool" "path_provider_ros_tool" "simulation_ros_tool" "tui_ros_tool" "vehicle_setup")
set(kal_BUILDTOOL_DEPENDS "catkin")
set(kal_BUILDTOOL_EXPORT_DEPENDS )
set(kal_EXEC_DEPENDS "demo_image_processing_ros_tool" "joy_converter_ros_tool" "lateral_control_ros_tool" "longitudinal_control_ros_tool" "motor_interface_ros_tool" "path_provider_ros_tool" "simulation_ros_tool" "tui_ros_tool" "vehicle_setup")
set(kal_RUN_DEPENDS "demo_image_processing_ros_tool" "joy_converter_ros_tool" "lateral_control_ros_tool" "longitudinal_control_ros_tool" "motor_interface_ros_tool" "path_provider_ros_tool" "simulation_ros_tool" "tui_ros_tool" "vehicle_setup")
set(kal_TEST_DEPENDS "gtest")
set(kal_DOC_DEPENDS )
set(kal_URL_WEBSITE "")
set(kal_URL_BUGTRACKER "")
set(kal_URL_REPOSITORY "git@gitlab.mrt.uni-karlsruhe.de:kognitive_automobile_labor/kal.git")
set(kal_DEPRECATED "")