// Generated by gencpp from file longitudinal_control_ros_tool/veloserviceResponse.msg
// DO NOT EDIT!


#ifndef LONGITUDINAL_CONTROL_ROS_TOOL_MESSAGE_VELOSERVICERESPONSE_H
#define LONGITUDINAL_CONTROL_ROS_TOOL_MESSAGE_VELOSERVICERESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace longitudinal_control_ros_tool
{
template <class ContainerAllocator>
struct veloserviceResponse_
{
  typedef veloserviceResponse_<ContainerAllocator> Type;

  veloserviceResponse_()
    {
    }
  veloserviceResponse_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::longitudinal_control_ros_tool::veloserviceResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::longitudinal_control_ros_tool::veloserviceResponse_<ContainerAllocator> const> ConstPtr;

}; // struct veloserviceResponse_

typedef ::longitudinal_control_ros_tool::veloserviceResponse_<std::allocator<void> > veloserviceResponse;

typedef boost::shared_ptr< ::longitudinal_control_ros_tool::veloserviceResponse > veloserviceResponsePtr;
typedef boost::shared_ptr< ::longitudinal_control_ros_tool::veloserviceResponse const> veloserviceResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::longitudinal_control_ros_tool::veloserviceResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::longitudinal_control_ros_tool::veloserviceResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace longitudinal_control_ros_tool

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::longitudinal_control_ros_tool::veloserviceResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::longitudinal_control_ros_tool::veloserviceResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::longitudinal_control_ros_tool::veloserviceResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::longitudinal_control_ros_tool::veloserviceResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::longitudinal_control_ros_tool::veloserviceResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::longitudinal_control_ros_tool::veloserviceResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::longitudinal_control_ros_tool::veloserviceResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::longitudinal_control_ros_tool::veloserviceResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::longitudinal_control_ros_tool::veloserviceResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "longitudinal_control_ros_tool/veloserviceResponse";
  }

  static const char* value(const ::longitudinal_control_ros_tool::veloserviceResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::longitudinal_control_ros_tool::veloserviceResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n\
";
  }

  static const char* value(const ::longitudinal_control_ros_tool::veloserviceResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::longitudinal_control_ros_tool::veloserviceResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct veloserviceResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::longitudinal_control_ros_tool::veloserviceResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::longitudinal_control_ros_tool::veloserviceResponse_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // LONGITUDINAL_CONTROL_ROS_TOOL_MESSAGE_VELOSERVICERESPONSE_H
