// Generated by gencpp from file longitudinal_control_ros_tool/veloserviceRequest.msg
// DO NOT EDIT!


#ifndef LONGITUDINAL_CONTROL_ROS_TOOL_MESSAGE_VELOSERVICEREQUEST_H
#define LONGITUDINAL_CONTROL_ROS_TOOL_MESSAGE_VELOSERVICEREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace longitudinal_control_ros_tool
{
template <class ContainerAllocator>
struct veloserviceRequest_
{
  typedef veloserviceRequest_<ContainerAllocator> Type;

  veloserviceRequest_()
    : activate(false)
    , velo(0.0)  {
    }
  veloserviceRequest_(const ContainerAllocator& _alloc)
    : activate(false)
    , velo(0.0)  {
  (void)_alloc;
    }



   typedef uint8_t _activate_type;
  _activate_type activate;

   typedef float _velo_type;
  _velo_type velo;





  typedef boost::shared_ptr< ::longitudinal_control_ros_tool::veloserviceRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::longitudinal_control_ros_tool::veloserviceRequest_<ContainerAllocator> const> ConstPtr;

}; // struct veloserviceRequest_

typedef ::longitudinal_control_ros_tool::veloserviceRequest_<std::allocator<void> > veloserviceRequest;

typedef boost::shared_ptr< ::longitudinal_control_ros_tool::veloserviceRequest > veloserviceRequestPtr;
typedef boost::shared_ptr< ::longitudinal_control_ros_tool::veloserviceRequest const> veloserviceRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::longitudinal_control_ros_tool::veloserviceRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::longitudinal_control_ros_tool::veloserviceRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace longitudinal_control_ros_tool

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::longitudinal_control_ros_tool::veloserviceRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::longitudinal_control_ros_tool::veloserviceRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::longitudinal_control_ros_tool::veloserviceRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::longitudinal_control_ros_tool::veloserviceRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::longitudinal_control_ros_tool::veloserviceRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::longitudinal_control_ros_tool::veloserviceRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::longitudinal_control_ros_tool::veloserviceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "50f8ae24fde2172b763492643402bd9d";
  }

  static const char* value(const ::longitudinal_control_ros_tool::veloserviceRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x50f8ae24fde2172bULL;
  static const uint64_t static_value2 = 0x763492643402bd9dULL;
};

template<class ContainerAllocator>
struct DataType< ::longitudinal_control_ros_tool::veloserviceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "longitudinal_control_ros_tool/veloserviceRequest";
  }

  static const char* value(const ::longitudinal_control_ros_tool::veloserviceRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::longitudinal_control_ros_tool::veloserviceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool activate\n\
float32 velo\n\
";
  }

  static const char* value(const ::longitudinal_control_ros_tool::veloserviceRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::longitudinal_control_ros_tool::veloserviceRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.activate);
      stream.next(m.velo);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct veloserviceRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::longitudinal_control_ros_tool::veloserviceRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::longitudinal_control_ros_tool::veloserviceRequest_<ContainerAllocator>& v)
  {
    s << indent << "activate: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.activate);
    s << indent << "velo: ";
    Printer<float>::stream(s, indent + "  ", v.velo);
  }
};

} // namespace message_operations
} // namespace ros

#endif // LONGITUDINAL_CONTROL_ROS_TOOL_MESSAGE_VELOSERVICEREQUEST_H
