set(_CATKIN_CURRENT_PACKAGE "path_provider_ros_tool")
set(path_provider_ros_tool_VERSION "1.0.0")
set(path_provider_ros_tool_MAINTAINER "Sascha Wirges <wirges@fzi.de>")
set(path_provider_ros_tool_PACKAGE_FORMAT "2")
set(path_provider_ros_tool_BUILD_DEPENDS "mrt_cmake_modules" "rosparam_handler" "message_generation" "roscpp" "roslib" "nodelet" "dynamic_reconfigure" "eigen" "eigen_conversions" "rosbag" "tf2_ros" "utils_ros")
set(path_provider_ros_tool_BUILD_EXPORT_DEPENDS "roslib" "nodelet" "dynamic_reconfigure" "eigen" "eigen_conversions" "rosbag" "tf2_ros" "utils_ros")
set(path_provider_ros_tool_BUILDTOOL_DEPENDS "catkin")
set(path_provider_ros_tool_BUILDTOOL_EXPORT_DEPENDS )
set(path_provider_ros_tool_EXEC_DEPENDS "message_runtime" "roslib" "nodelet" "dynamic_reconfigure" "eigen" "eigen_conversions" "rosbag" "tf2_ros" "utils_ros")
set(path_provider_ros_tool_RUN_DEPENDS "message_runtime" "roslib" "nodelet" "dynamic_reconfigure" "eigen" "eigen_conversions" "rosbag" "tf2_ros" "utils_ros")
set(path_provider_ros_tool_TEST_DEPENDS "gtest" "rostest")
set(path_provider_ros_tool_DOC_DEPENDS )
set(path_provider_ros_tool_URL_WEBSITE "")
set(path_provider_ros_tool_URL_BUGTRACKER "")
set(path_provider_ros_tool_URL_REPOSITORY "git@gitlab.mrt.uni-karlsruhe.de:kognitive_automobile_labor/path_provider_ros_tool.git")
set(path_provider_ros_tool_DEPRECATED "")