// *********************************************************
//
// File autogenerated for the simulation_ros_tool package
// by the rosparam_handler package.
// Please do not edit.
//
// ********************************************************/

#pragma once

#include <stdlib.h>
#include <string>
#include <limits>
#include <ros/param.h>
#include <ros/node_handle.h>
#ifdef DYNAMIC_RECONFIGURE_FOUND
#include <simulation_ros_tool/VehicleSimulatorConfig.h>
#else
struct VehicleSimulatorConfig{};
#endif


namespace simulation_ros_tool {

inline std::string getNodeName(const ros::NodeHandle& privateNodeHandle){
    std::string name_space = privateNodeHandle.getNamespace();
    std::stringstream tempString(name_space);
    std::string name;
    while(std::getline(tempString, name, '/')){;}
    return name;
}

template <typename T>
std::ostream& operator<< (std::ostream& out, const std::vector<T>& v) {
  if ( !v.empty() ) {
    out << '[';
    std::copy (v.begin(), v.end(), std::ostream_iterator<T>(out, ", "));
    out << "\b\b]";
  }
  return out;
}

template<typename T1, typename T2>
std::ostream &operator<<(std::ostream &stream, const std::map<T1, T2>& map)
{
  stream << '{';
  for (typename std::map<T1, T2>::const_iterator it = map.begin();
       it != map.end();
       ++it)
    {
      stream << (*it).first << " --> " << (*it).second << ", ";
    }
  stream << '}';
  return stream;
}

struct VehicleSimulatorParameters {

  using Config = VehicleSimulatorConfig;

  VehicleSimulatorParameters(const ros::NodeHandle& private_node_handle)
  : globalNamespace{"/"},
    privateNamespace{private_node_handle.getNamespace() + "/"},
    nodeName{getNodeName(private_node_handle)} {}

  void fromParamServer(){
    getParam(privateNamespace + "verbosity", verbosity, std::string{"info"});
    getParam(privateNamespace + "msg_queue_size", msg_queue_size, int{1});
    getParam(privateNamespace + "motor_command_topic", motor_command_topic, std::string{"motor_command"});
    getParam(privateNamespace + "servo_command_topic", servo_command_topic, std::string{"servo_command"});
    getParam(privateNamespace + "wheel_base", wheel_base, double{0.5});
    getParam(privateNamespace + "tf_refresh_rate", tf_refresh_rate, double{60});
    getParam(privateNamespace + "map_frame", map_frame, std::string{"world"});
    getParam(privateNamespace + "vehicle_frame", vehicle_frame, std::string{"vehicle_rear_axle"});
    getParam(privateNamespace + "initial_x", initial_x, double{0.0});
    getParam(privateNamespace + "initial_y", initial_y, double{0.0});
    getParam(privateNamespace + "initial_yaw", initial_yaw, double{0.0});

    testMin<double>(privateNamespace + "wheel_base", wheel_base, 0);
    testMax<double>(privateNamespace + "wheel_base", wheel_base, 1);
    testMin<double>(privateNamespace + "tf_refresh_rate", tf_refresh_rate, 0);
    testMax<double>(privateNamespace + "tf_refresh_rate", tf_refresh_rate, 100);
  ROS_DEBUG_STREAM(*this);
  }

  void fromConfig(const Config& config, const uint32_t level = 0){
#ifdef DYNAMIC_RECONFIGURE_FOUND
    wheel_base = config.wheel_base;
    tf_refresh_rate = config.tf_refresh_rate;
#else
  ROS_FATAL_STREAM("dynamic_reconfigure was not found during compilation. So fromConfig() is not available. Please recompile with dynamic_reconfigure.");
  std::exit(EXIT_FAILURE);
#endif
  }

  friend std::ostream& operator<<(std::ostream& os, const VehicleSimulatorParameters& p)
  {
    os << "[" << p.nodeName << "]\nNode " << p.nodeName << " has the following parameters:\n"
      << "	" << p.privateNamespace << "verbosity:" << p.verbosity << "\n"
      << "	" << p.privateNamespace << "msg_queue_size:" << p.msg_queue_size << "\n"
      << "	" << p.privateNamespace << "motor_command_topic:" << p.motor_command_topic << "\n"
      << "	" << p.privateNamespace << "servo_command_topic:" << p.servo_command_topic << "\n"
      << "	" << p.privateNamespace << "wheel_base:" << p.wheel_base << "\n"
      << "	" << p.privateNamespace << "tf_refresh_rate:" << p.tf_refresh_rate << "\n"
      << "	" << p.privateNamespace << "map_frame:" << p.map_frame << "\n"
      << "	" << p.privateNamespace << "vehicle_frame:" << p.vehicle_frame << "\n"
      << "	" << p.privateNamespace << "initial_x:" << p.initial_x << "\n"
      << "	" << p.privateNamespace << "initial_y:" << p.initial_y << "\n"
      << "	" << p.privateNamespace << "initial_yaw:" << p.initial_yaw << "\n"
;
    return os;
  }

  void missingParamsWarning(){
    ROS_WARN_STREAM("[" << nodeName << "]\nThe following parameters do not have default values and need to be specified:\n"
    );
  }

  template <typename T>
  void getParam(const std::string key, T& val) {
    if (!ros::param::has(key)) {
      ROS_ERROR_STREAM("Parameter '" << key << "' is not defined.");
      missingParamsWarning();
      std::exit(EXIT_FAILURE);
    } else if (!ros::param::get(key, val)) {
      ROS_ERROR_STREAM("Could not retrieve parameter'" << key << "'. Does it have a different type?");
      missingParamsWarning();
      std::exit(EXIT_FAILURE);
    }
  }

  template <typename T>
  void getParam(const std::string key, T& val, const T& defaultValue) {
    if (!ros::param::has(key)) {
        val = defaultValue;
        ros::param::set(key, defaultValue);
        ROS_INFO_STREAM("Parameter "<<key<<" is not yet set. Setting default value.");
    } else if (!ros::param::get(key, val)) {
        ROS_WARN_STREAM("Parameter "<<key<<" is set, but has a different type. Using default value instead.");
        val = defaultValue;
	}
  }

  void testConstParam(const std::string key){
    if (ros::param::has(key)) {
      ROS_WARN_STREAM("Parameter " << key << "' was set on the parameter server eventhough it was defined to be constant.");
    }
  }

  template<typename T>
  void testMin(const std::string key, T& val, T min = std::numeric_limits<T>::min()){
    if (val < min){
      ROS_WARN_STREAM("Value of " << val << " for " << key << " is smaller than minimal allowed value. Correcting value to min=" << min);
      val = min;
    }
  }

  template<typename T>
  void testMax(const std::string key, T& val, T max = std::numeric_limits<T>::max()){
    if (val > max){
      ROS_WARN_STREAM("Value of " << val << " for " << key << " is greater than maximal allowed. Correcting value to max=" << max);
      val = max;
    }
  }

    std::string verbosity; /*!< Set logger level for this node */
  int msg_queue_size; /*!< queue size of the motor command subscriber */
  std::string motor_command_topic; /*!< Topicname for motor command subscriber */
  std::string servo_command_topic; /*!< Topicname for servo command subscriber */
  double wheel_base; /*!< cars wheel_base */
  double tf_refresh_rate; /*!< rate to refresh the transformation at */
  std::string map_frame; /*!< frame of the map (e.g. 'world') */
  std::string vehicle_frame; /*!< frame of the vehicles rear axle (e.g. 'vehicle_rear_axle') */
  double initial_x; /*!< initial x value of the pose */
  double initial_y; /*!< initial y value of the pose */
  double initial_yaw; /*!< initial yaw angle of the pose */

  private:
    const std::string globalNamespace;
    const std::string privateNamespace;
    const std::string nodeName;
};

} // namespace simulation_ros_tool
