set(_CATKIN_CURRENT_PACKAGE "image_preproc")
set(image_preproc_VERSION "0.0.0")
set(image_preproc_MAINTAINER "Eike Rehder <eike.rehder@kit.edu>")
set(image_preproc_PACKAGE_FORMAT "2")
set(image_preproc_BUILD_DEPENDS "mrt_cmake_modules" "mrt_opencv")
set(image_preproc_BUILD_EXPORT_DEPENDS "mrt_opencv")
set(image_preproc_BUILDTOOL_DEPENDS "catkin")
set(image_preproc_BUILDTOOL_EXPORT_DEPENDS )
set(image_preproc_EXEC_DEPENDS "mrt_opencv")
set(image_preproc_RUN_DEPENDS "mrt_opencv")
set(image_preproc_TEST_DEPENDS "gtest")
set(image_preproc_DOC_DEPENDS )
set(image_preproc_URL_WEBSITE "")
set(image_preproc_URL_BUGTRACKER "")
set(image_preproc_URL_REPOSITORY "https://gitlab.mrt.uni-karlsruhe.de/MRT/image_preproc.git")
set(image_preproc_DEPRECATED "")