set(_CATKIN_CURRENT_PACKAGE "utils_ros")
set(utils_ros_VERSION "1.0.0")
set(utils_ros_MAINTAINER "Andre-Marcel Hellmund <andre-marcel.hellmund@kit.edu>")
set(utils_ros_PACKAGE_FORMAT "2")
set(utils_ros_BUILD_DEPENDS "mrt_cmake_modules" "message_generation" "roscpp" "roslib" "message_filters" "geometry_msgs" "boost")
set(utils_ros_BUILD_EXPORT_DEPENDS "roscpp" "roslib" "message_filters" "geometry_msgs" "boost")
set(utils_ros_BUILDTOOL_DEPENDS "catkin")
set(utils_ros_BUILDTOOL_EXPORT_DEPENDS )
set(utils_ros_EXEC_DEPENDS "message_runtime" "roscpp" "roslib" "message_filters" "geometry_msgs" "boost")
set(utils_ros_RUN_DEPENDS "message_runtime" "roscpp" "roslib" "message_filters" "geometry_msgs" "boost")
set(utils_ros_TEST_DEPENDS "gtest" "rostest" "image_transport")
set(utils_ros_DOC_DEPENDS )
set(utils_ros_URL_WEBSITE "")
set(utils_ros_URL_BUGTRACKER "")
set(utils_ros_URL_REPOSITORY "https://gitlab.mrt.uni-karlsruhe.de/MRT/utils_ros.git")
set(utils_ros_DEPRECATED "")