set(_CATKIN_CURRENT_PACKAGE "prosilica_driver")
set(prosilica_driver_VERSION "1.9.4")
set(prosilica_driver_MAINTAINER "Austin Hendrix <namniart@gmail.com>")
set(prosilica_driver_PACKAGE_FORMAT "1")
set(prosilica_driver_BUILD_DEPENDS "prosilica_gige_sdk" "roscpp" "std_msgs" "sensor_msgs" "diagnostic_updater" "diagnostic_msgs" "image_transport" "self_test" "driver_base" "dynamic_reconfigure" "camera_calibration_parsers" "polled_camera" "rosconsole" "nodelet" "nodelet_topic_tools")
set(prosilica_driver_BUILD_EXPORT_DEPENDS "prosilica_gige_sdk" "roscpp" "std_msgs" "sensor_msgs" "diagnostic_updater" "diagnostic_msgs" "image_transport" "self_test" "driver_base" "dynamic_reconfigure" "camera_calibration_parsers" "polled_camera" "nodelet" "nodelet_topic_tools")
set(prosilica_driver_BUILDTOOL_DEPENDS "catkin")
set(prosilica_driver_BUILDTOOL_EXPORT_DEPENDS )
set(prosilica_driver_EXEC_DEPENDS "prosilica_gige_sdk" "roscpp" "std_msgs" "sensor_msgs" "diagnostic_updater" "diagnostic_msgs" "image_transport" "self_test" "driver_base" "dynamic_reconfigure" "camera_calibration_parsers" "polled_camera" "nodelet" "nodelet_topic_tools")
set(prosilica_driver_RUN_DEPENDS "prosilica_gige_sdk" "roscpp" "std_msgs" "sensor_msgs" "diagnostic_updater" "diagnostic_msgs" "image_transport" "self_test" "driver_base" "dynamic_reconfigure" "camera_calibration_parsers" "polled_camera" "nodelet" "nodelet_topic_tools")
set(prosilica_driver_TEST_DEPENDS )
set(prosilica_driver_DOC_DEPENDS )
set(prosilica_driver_URL_WEBSITE "http://www.ros.org/wiki/prosilica_camera")
set(prosilica_driver_URL_BUGTRACKER "")
set(prosilica_driver_URL_REPOSITORY "")
set(prosilica_driver_DEPRECATED "")