// Generated by gencpp from file stargazer_ros_tool/Landmark.msg
// DO NOT EDIT!


#ifndef STARGAZER_ROS_TOOL_MESSAGE_LANDMARK_H
#define STARGAZER_ROS_TOOL_MESSAGE_LANDMARK_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <stargazer_ros_tool/LandmarkPoint.h>
#include <stargazer_ros_tool/LandmarkPoint.h>

namespace stargazer_ros_tool
{
template <class ContainerAllocator>
struct Landmark_
{
  typedef Landmark_<ContainerAllocator> Type;

  Landmark_()
    : header()
    , id(0)
    , corner_points()
    , id_points()  {
    }
  Landmark_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , id(0)
    , corner_points(_alloc)
    , id_points(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef int32_t _id_type;
  _id_type id;

   typedef std::vector< ::stargazer_ros_tool::LandmarkPoint_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::stargazer_ros_tool::LandmarkPoint_<ContainerAllocator> >::other >  _corner_points_type;
  _corner_points_type corner_points;

   typedef std::vector< ::stargazer_ros_tool::LandmarkPoint_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::stargazer_ros_tool::LandmarkPoint_<ContainerAllocator> >::other >  _id_points_type;
  _id_points_type id_points;





  typedef boost::shared_ptr< ::stargazer_ros_tool::Landmark_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::stargazer_ros_tool::Landmark_<ContainerAllocator> const> ConstPtr;

}; // struct Landmark_

typedef ::stargazer_ros_tool::Landmark_<std::allocator<void> > Landmark;

typedef boost::shared_ptr< ::stargazer_ros_tool::Landmark > LandmarkPtr;
typedef boost::shared_ptr< ::stargazer_ros_tool::Landmark const> LandmarkConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::stargazer_ros_tool::Landmark_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::stargazer_ros_tool::Landmark_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace stargazer_ros_tool

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'stargazer_ros_tool': ['/home/kal5-1/cargogo/src/stargazer_ros_tool/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::stargazer_ros_tool::Landmark_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::stargazer_ros_tool::Landmark_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::stargazer_ros_tool::Landmark_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::stargazer_ros_tool::Landmark_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::stargazer_ros_tool::Landmark_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::stargazer_ros_tool::Landmark_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::stargazer_ros_tool::Landmark_<ContainerAllocator> >
{
  static const char* value()
  {
    return "1cd8dba4674c7e54a53fc21b6eccc87c";
  }

  static const char* value(const ::stargazer_ros_tool::Landmark_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x1cd8dba4674c7e54ULL;
  static const uint64_t static_value2 = 0xa53fc21b6eccc87cULL;
};

template<class ContainerAllocator>
struct DataType< ::stargazer_ros_tool::Landmark_<ContainerAllocator> >
{
  static const char* value()
  {
    return "stargazer_ros_tool/Landmark";
  }

  static const char* value(const ::stargazer_ros_tool::Landmark_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::stargazer_ros_tool::Landmark_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
int32 id\n\
LandmarkPoint[] corner_points\n\
LandmarkPoint[] id_points\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: stargazer_ros_tool/LandmarkPoint\n\
uint8 row\n\
uint8 col\n\
\n\
uint16 u\n\
uint16 v\n\
";
  }

  static const char* value(const ::stargazer_ros_tool::Landmark_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::stargazer_ros_tool::Landmark_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.id);
      stream.next(m.corner_points);
      stream.next(m.id_points);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Landmark_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::stargazer_ros_tool::Landmark_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::stargazer_ros_tool::Landmark_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "id: ";
    Printer<int32_t>::stream(s, indent + "  ", v.id);
    s << indent << "corner_points[]" << std::endl;
    for (size_t i = 0; i < v.corner_points.size(); ++i)
    {
      s << indent << "  corner_points[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::stargazer_ros_tool::LandmarkPoint_<ContainerAllocator> >::stream(s, indent + "    ", v.corner_points[i]);
    }
    s << indent << "id_points[]" << std::endl;
    for (size_t i = 0; i < v.id_points.size(); ++i)
    {
      s << indent << "  id_points[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::stargazer_ros_tool::LandmarkPoint_<ContainerAllocator> >::stream(s, indent + "    ", v.id_points[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // STARGAZER_ROS_TOOL_MESSAGE_LANDMARK_H
