//#line 2 "/opt/ros/kinetic/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"
// *********************************************************
//
// File autogenerated for the stargazer_ros_tool package
// by the dynamic_reconfigure package.
// Please do not edit.
//
// ********************************************************/

#ifndef __stargazer_ros_tool__LANDMARKFINDERCONFIG_H__
#define __stargazer_ros_tool__LANDMARKFINDERCONFIG_H__

#include <dynamic_reconfigure/config_tools.h>
#include <limits>
#include <ros/node_handle.h>
#include <dynamic_reconfigure/ConfigDescription.h>
#include <dynamic_reconfigure/ParamDescription.h>
#include <dynamic_reconfigure/Group.h>
#include <dynamic_reconfigure/config_init_mutex.h>
#include <boost/any.hpp>

namespace stargazer_ros_tool
{
  class LandmarkFinderConfigStatics;

  class LandmarkFinderConfig
  {
  public:
    class AbstractParamDescription : public dynamic_reconfigure::ParamDescription
    {
    public:
      AbstractParamDescription(std::string n, std::string t, uint32_t l,
          std::string d, std::string e)
      {
        name = n;
        type = t;
        level = l;
        description = d;
        edit_method = e;
      }

      virtual void clamp(LandmarkFinderConfig &config, const LandmarkFinderConfig &max, const LandmarkFinderConfig &min) const = 0;
      virtual void calcLevel(uint32_t &level, const LandmarkFinderConfig &config1, const LandmarkFinderConfig &config2) const = 0;
      virtual void fromServer(const ros::NodeHandle &nh, LandmarkFinderConfig &config) const = 0;
      virtual void toServer(const ros::NodeHandle &nh, const LandmarkFinderConfig &config) const = 0;
      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, LandmarkFinderConfig &config) const = 0;
      virtual void toMessage(dynamic_reconfigure::Config &msg, const LandmarkFinderConfig &config) const = 0;
      virtual void getValue(const LandmarkFinderConfig &config, boost::any &val) const = 0;
    };

    typedef boost::shared_ptr<AbstractParamDescription> AbstractParamDescriptionPtr;
    typedef boost::shared_ptr<const AbstractParamDescription> AbstractParamDescriptionConstPtr;

    template <class T>
    class ParamDescription : public AbstractParamDescription
    {
    public:
      ParamDescription(std::string a_name, std::string a_type, uint32_t a_level,
          std::string a_description, std::string a_edit_method, T LandmarkFinderConfig::* a_f) :
        AbstractParamDescription(a_name, a_type, a_level, a_description, a_edit_method),
        field(a_f)
      {}

      T (LandmarkFinderConfig::* field);

      virtual void clamp(LandmarkFinderConfig &config, const LandmarkFinderConfig &max, const LandmarkFinderConfig &min) const
      {
        if (config.*field > max.*field)
          config.*field = max.*field;

        if (config.*field < min.*field)
          config.*field = min.*field;
      }

      virtual void calcLevel(uint32_t &comb_level, const LandmarkFinderConfig &config1, const LandmarkFinderConfig &config2) const
      {
        if (config1.*field != config2.*field)
          comb_level |= level;
      }

      virtual void fromServer(const ros::NodeHandle &nh, LandmarkFinderConfig &config) const
      {
        nh.getParam(name, config.*field);
      }

      virtual void toServer(const ros::NodeHandle &nh, const LandmarkFinderConfig &config) const
      {
        nh.setParam(name, config.*field);
      }

      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, LandmarkFinderConfig &config) const
      {
        return dynamic_reconfigure::ConfigTools::getParameter(msg, name, config.*field);
      }

      virtual void toMessage(dynamic_reconfigure::Config &msg, const LandmarkFinderConfig &config) const
      {
        dynamic_reconfigure::ConfigTools::appendParameter(msg, name, config.*field);
      }

      virtual void getValue(const LandmarkFinderConfig &config, boost::any &val) const
      {
        val = config.*field;
      }
    };

    class AbstractGroupDescription : public dynamic_reconfigure::Group
    {
      public:
      AbstractGroupDescription(std::string n, std::string t, int p, int i, bool s)
      {
        name = n;
        type = t;
        parent = p;
        state = s;
        id = i;
      }

      std::vector<AbstractParamDescriptionConstPtr> abstract_parameters;
      bool state;

      virtual void toMessage(dynamic_reconfigure::Config &msg, const boost::any &config) const = 0;
      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, boost::any &config) const =0;
      virtual void updateParams(boost::any &cfg, LandmarkFinderConfig &top) const= 0;
      virtual void setInitialState(boost::any &cfg) const = 0;


      void convertParams()
      {
        for(std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = abstract_parameters.begin(); i != abstract_parameters.end(); ++i)
        {
          parameters.push_back(dynamic_reconfigure::ParamDescription(**i));
        }
      }
    };

    typedef boost::shared_ptr<AbstractGroupDescription> AbstractGroupDescriptionPtr;
    typedef boost::shared_ptr<const AbstractGroupDescription> AbstractGroupDescriptionConstPtr;

    template<class T, class PT>
    class GroupDescription : public AbstractGroupDescription
    {
    public:
      GroupDescription(std::string a_name, std::string a_type, int a_parent, int a_id, bool a_s, T PT::* a_f) : AbstractGroupDescription(a_name, a_type, a_parent, a_id, a_s), field(a_f)
      {
      }

      GroupDescription(const GroupDescription<T, PT>& g): AbstractGroupDescription(g.name, g.type, g.parent, g.id, g.state), field(g.field), groups(g.groups)
      {
        parameters = g.parameters;
        abstract_parameters = g.abstract_parameters;
      }

      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, boost::any &cfg) const
      {
        PT* config = boost::any_cast<PT*>(cfg);
        if(!dynamic_reconfigure::ConfigTools::getGroupState(msg, name, (*config).*field))
          return false;

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = &((*config).*field);
          if(!(*i)->fromMessage(msg, n))
            return false;
        }

        return true;
      }

      virtual void setInitialState(boost::any &cfg) const
      {
        PT* config = boost::any_cast<PT*>(cfg);
        T* group = &((*config).*field);
        group->state = state;

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = boost::any(&((*config).*field));
          (*i)->setInitialState(n);
        }

      }

      virtual void updateParams(boost::any &cfg, LandmarkFinderConfig &top) const
      {
        PT* config = boost::any_cast<PT*>(cfg);

        T* f = &((*config).*field);
        f->setParams(top, abstract_parameters);

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = &((*config).*field);
          (*i)->updateParams(n, top);
        }
      }

      virtual void toMessage(dynamic_reconfigure::Config &msg, const boost::any &cfg) const
      {
        const PT config = boost::any_cast<PT>(cfg);
        dynamic_reconfigure::ConfigTools::appendGroup<T>(msg, name, id, parent, config.*field);

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          (*i)->toMessage(msg, config.*field);
        }
      }

      T (PT::* field);
      std::vector<LandmarkFinderConfig::AbstractGroupDescriptionConstPtr> groups;
    };

class DEFAULT
{
  public:
    DEFAULT()
    {
      state = true;
      name = "Default";
    }

    void setParams(LandmarkFinderConfig &config, const std::vector<AbstractParamDescriptionConstPtr> params)
    {
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator _i = params.begin(); _i != params.end(); ++_i)
      {
        boost::any val;
        (*_i)->getValue(config, val);

        if("tight_filter_size"==(*_i)->name){tight_filter_size = boost::any_cast<int>(val);}
        if("wide_filter_size"==(*_i)->name){wide_filter_size = boost::any_cast<int>(val);}
        if("threshold"==(*_i)->name){threshold = boost::any_cast<int>(val);}
        if("maxRadiusForPixelCluster"==(*_i)->name){maxRadiusForPixelCluster = boost::any_cast<double>(val);}
        if("maxRadiusForCluster"==(*_i)->name){maxRadiusForCluster = boost::any_cast<double>(val);}
        if("minPixelForCluster"==(*_i)->name){minPixelForCluster = boost::any_cast<int>(val);}
        if("maxPixelForCluster"==(*_i)->name){maxPixelForCluster = boost::any_cast<int>(val);}
        if("minPointsPerLandmark"==(*_i)->name){minPointsPerLandmark = boost::any_cast<int>(val);}
        if("maxPointsPerLandmark"==(*_i)->name){maxPointsPerLandmark = boost::any_cast<int>(val);}
        if("debug_mode"==(*_i)->name){debug_mode = boost::any_cast<bool>(val);}
      }
    }

    int tight_filter_size;
int wide_filter_size;
int threshold;
double maxRadiusForPixelCluster;
double maxRadiusForCluster;
int minPixelForCluster;
int maxPixelForCluster;
int minPointsPerLandmark;
int maxPointsPerLandmark;
bool debug_mode;

    bool state;
    std::string name;

    
}groups;



//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int tight_filter_size;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int wide_filter_size;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int threshold;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double maxRadiusForPixelCluster;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double maxRadiusForCluster;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int minPixelForCluster;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int maxPixelForCluster;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int minPointsPerLandmark;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int maxPointsPerLandmark;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      bool debug_mode;
//#line 218 "/opt/ros/kinetic/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"

    bool __fromMessage__(dynamic_reconfigure::Config &msg)
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();

      int count = 0;
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        if ((*i)->fromMessage(msg, *this))
          count++;

      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); i ++)
      {
        if ((*i)->id == 0)
        {
          boost::any n = boost::any(this);
          (*i)->updateParams(n, *this);
          (*i)->fromMessage(msg, n);
        }
      }

      if (count != dynamic_reconfigure::ConfigTools::size(msg))
      {
        ROS_ERROR("LandmarkFinderConfig::__fromMessage__ called with an unexpected parameter.");
        ROS_ERROR("Booleans:");
        for (unsigned int i = 0; i < msg.bools.size(); i++)
          ROS_ERROR("  %s", msg.bools[i].name.c_str());
        ROS_ERROR("Integers:");
        for (unsigned int i = 0; i < msg.ints.size(); i++)
          ROS_ERROR("  %s", msg.ints[i].name.c_str());
        ROS_ERROR("Doubles:");
        for (unsigned int i = 0; i < msg.doubles.size(); i++)
          ROS_ERROR("  %s", msg.doubles[i].name.c_str());
        ROS_ERROR("Strings:");
        for (unsigned int i = 0; i < msg.strs.size(); i++)
          ROS_ERROR("  %s", msg.strs[i].name.c_str());
        // @todo Check that there are no duplicates. Make this error more
        // explicit.
        return false;
      }
      return true;
    }

    // This version of __toMessage__ is used during initialization of
    // statics when __getParamDescriptions__ can't be called yet.
    void __toMessage__(dynamic_reconfigure::Config &msg, const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__, const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__) const
    {
      dynamic_reconfigure::ConfigTools::clear(msg);
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->toMessage(msg, *this);

      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); ++i)
      {
        if((*i)->id == 0)
        {
          (*i)->toMessage(msg, *this);
        }
      }
    }

    void __toMessage__(dynamic_reconfigure::Config &msg) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();
      __toMessage__(msg, __param_descriptions__, __group_descriptions__);
    }

    void __toServer__(const ros::NodeHandle &nh) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->toServer(nh, *this);
    }

    void __fromServer__(const ros::NodeHandle &nh)
    {
      static bool setup=false;

      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->fromServer(nh, *this);

      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();
      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); i++){
        if (!setup && (*i)->id == 0) {
          setup = true;
          boost::any n = boost::any(this);
          (*i)->setInitialState(n);
        }
      }
    }

    void __clamp__()
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const LandmarkFinderConfig &__max__ = __getMax__();
      const LandmarkFinderConfig &__min__ = __getMin__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->clamp(*this, __max__, __min__);
    }

    uint32_t __level__(const LandmarkFinderConfig &config) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      uint32_t level = 0;
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->calcLevel(level, config, *this);
      return level;
    }

    static const dynamic_reconfigure::ConfigDescription &__getDescriptionMessage__();
    static const LandmarkFinderConfig &__getDefault__();
    static const LandmarkFinderConfig &__getMax__();
    static const LandmarkFinderConfig &__getMin__();
    static const std::vector<AbstractParamDescriptionConstPtr> &__getParamDescriptions__();
    static const std::vector<AbstractGroupDescriptionConstPtr> &__getGroupDescriptions__();

  private:
    static const LandmarkFinderConfigStatics *__get_statics__();
  };

  template <> // Max and min are ignored for strings.
  inline void LandmarkFinderConfig::ParamDescription<std::string>::clamp(LandmarkFinderConfig &config, const LandmarkFinderConfig &max, const LandmarkFinderConfig &min) const
  {
    (void) config;
    (void) min;
    (void) max;
    return;
  }

  class LandmarkFinderConfigStatics
  {
    friend class LandmarkFinderConfig;

    LandmarkFinderConfigStatics()
    {
LandmarkFinderConfig::GroupDescription<LandmarkFinderConfig::DEFAULT, LandmarkFinderConfig> Default("Default", "", 0, 0, true, &LandmarkFinderConfig::groups);
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.tight_filter_size = 0;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.tight_filter_size = 255;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.tight_filter_size = 0;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(LandmarkFinderConfig::AbstractParamDescriptionConstPtr(new LandmarkFinderConfig::ParamDescription<int>("tight_filter_size", "int", 0, "Size of the tighter box filter of DOB", "", &LandmarkFinderConfig::tight_filter_size)));
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(LandmarkFinderConfig::AbstractParamDescriptionConstPtr(new LandmarkFinderConfig::ParamDescription<int>("tight_filter_size", "int", 0, "Size of the tighter box filter of DOB", "", &LandmarkFinderConfig::tight_filter_size)));
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.wide_filter_size = 0;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.wide_filter_size = 255;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.wide_filter_size = 0;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(LandmarkFinderConfig::AbstractParamDescriptionConstPtr(new LandmarkFinderConfig::ParamDescription<int>("wide_filter_size", "int", 0, "Size of the wider box filter of DOB", "", &LandmarkFinderConfig::wide_filter_size)));
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(LandmarkFinderConfig::AbstractParamDescriptionConstPtr(new LandmarkFinderConfig::ParamDescription<int>("wide_filter_size", "int", 0, "Size of the wider box filter of DOB", "", &LandmarkFinderConfig::wide_filter_size)));
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.threshold = 0;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.threshold = 255;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.threshold = 0;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(LandmarkFinderConfig::AbstractParamDescriptionConstPtr(new LandmarkFinderConfig::ParamDescription<int>("threshold", "int", 0, "Grayvalue threshold for landmark detection", "", &LandmarkFinderConfig::threshold)));
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(LandmarkFinderConfig::AbstractParamDescriptionConstPtr(new LandmarkFinderConfig::ParamDescription<int>("threshold", "int", 0, "Grayvalue threshold for landmark detection", "", &LandmarkFinderConfig::threshold)));
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.maxRadiusForPixelCluster = 0.0;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.maxRadiusForPixelCluster = 2000.0;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.maxRadiusForPixelCluster = 0.0;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(LandmarkFinderConfig::AbstractParamDescriptionConstPtr(new LandmarkFinderConfig::ParamDescription<double>("maxRadiusForPixelCluster", "double", 0, "Maximum radius for clustering of pixels to points", "", &LandmarkFinderConfig::maxRadiusForPixelCluster)));
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(LandmarkFinderConfig::AbstractParamDescriptionConstPtr(new LandmarkFinderConfig::ParamDescription<double>("maxRadiusForPixelCluster", "double", 0, "Maximum radius for clustering of pixels to points", "", &LandmarkFinderConfig::maxRadiusForPixelCluster)));
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.maxRadiusForCluster = 0.0;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.maxRadiusForCluster = 2000.0;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.maxRadiusForCluster = 0.0;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(LandmarkFinderConfig::AbstractParamDescriptionConstPtr(new LandmarkFinderConfig::ParamDescription<double>("maxRadiusForCluster", "double", 0, "Maximum radius for clustering of points to landmarks", "", &LandmarkFinderConfig::maxRadiusForCluster)));
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(LandmarkFinderConfig::AbstractParamDescriptionConstPtr(new LandmarkFinderConfig::ParamDescription<double>("maxRadiusForCluster", "double", 0, "Maximum radius for clustering of points to landmarks", "", &LandmarkFinderConfig::maxRadiusForCluster)));
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.minPixelForCluster = 0;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.minPixelForCluster = 2000;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.minPixelForCluster = 0;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(LandmarkFinderConfig::AbstractParamDescriptionConstPtr(new LandmarkFinderConfig::ParamDescription<int>("minPixelForCluster", "int", 0, "Minimum count of pixels per point", "", &LandmarkFinderConfig::minPixelForCluster)));
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(LandmarkFinderConfig::AbstractParamDescriptionConstPtr(new LandmarkFinderConfig::ParamDescription<int>("minPixelForCluster", "int", 0, "Minimum count of pixels per point", "", &LandmarkFinderConfig::minPixelForCluster)));
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.maxPixelForCluster = 0;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.maxPixelForCluster = 2000;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.maxPixelForCluster = 0;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(LandmarkFinderConfig::AbstractParamDescriptionConstPtr(new LandmarkFinderConfig::ParamDescription<int>("maxPixelForCluster", "int", 0, "Maximum count of pixels per point", "", &LandmarkFinderConfig::maxPixelForCluster)));
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(LandmarkFinderConfig::AbstractParamDescriptionConstPtr(new LandmarkFinderConfig::ParamDescription<int>("maxPixelForCluster", "int", 0, "Maximum count of pixels per point", "", &LandmarkFinderConfig::maxPixelForCluster)));
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.minPointsPerLandmark = 0;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.minPointsPerLandmark = 2000;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.minPointsPerLandmark = 0;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(LandmarkFinderConfig::AbstractParamDescriptionConstPtr(new LandmarkFinderConfig::ParamDescription<int>("minPointsPerLandmark", "int", 0, "Minimum count of points per landmark", "", &LandmarkFinderConfig::minPointsPerLandmark)));
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(LandmarkFinderConfig::AbstractParamDescriptionConstPtr(new LandmarkFinderConfig::ParamDescription<int>("minPointsPerLandmark", "int", 0, "Minimum count of points per landmark", "", &LandmarkFinderConfig::minPointsPerLandmark)));
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.maxPointsPerLandmark = 0;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.maxPointsPerLandmark = 2000;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.maxPointsPerLandmark = 0;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(LandmarkFinderConfig::AbstractParamDescriptionConstPtr(new LandmarkFinderConfig::ParamDescription<int>("maxPointsPerLandmark", "int", 0, "Maximum count of points per landmark", "", &LandmarkFinderConfig::maxPointsPerLandmark)));
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(LandmarkFinderConfig::AbstractParamDescriptionConstPtr(new LandmarkFinderConfig::ParamDescription<int>("maxPointsPerLandmark", "int", 0, "Maximum count of points per landmark", "", &LandmarkFinderConfig::maxPointsPerLandmark)));
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.debug_mode = 0;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.debug_mode = 1;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.debug_mode = 0;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(LandmarkFinderConfig::AbstractParamDescriptionConstPtr(new LandmarkFinderConfig::ParamDescription<bool>("debug_mode", "bool", 0, "Activate debug mode for landmark finder to show results", "", &LandmarkFinderConfig::debug_mode)));
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(LandmarkFinderConfig::AbstractParamDescriptionConstPtr(new LandmarkFinderConfig::ParamDescription<bool>("debug_mode", "bool", 0, "Activate debug mode for landmark finder to show results", "", &LandmarkFinderConfig::debug_mode)));
//#line 245 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.convertParams();
//#line 245 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __group_descriptions__.push_back(LandmarkFinderConfig::AbstractGroupDescriptionConstPtr(new LandmarkFinderConfig::GroupDescription<LandmarkFinderConfig::DEFAULT, LandmarkFinderConfig>(Default)));
//#line 356 "/opt/ros/kinetic/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"

      for (std::vector<LandmarkFinderConfig::AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); ++i)
      {
        __description_message__.groups.push_back(**i);
      }
      __max__.__toMessage__(__description_message__.max, __param_descriptions__, __group_descriptions__);
      __min__.__toMessage__(__description_message__.min, __param_descriptions__, __group_descriptions__);
      __default__.__toMessage__(__description_message__.dflt, __param_descriptions__, __group_descriptions__);
    }
    std::vector<LandmarkFinderConfig::AbstractParamDescriptionConstPtr> __param_descriptions__;
    std::vector<LandmarkFinderConfig::AbstractGroupDescriptionConstPtr> __group_descriptions__;
    LandmarkFinderConfig __max__;
    LandmarkFinderConfig __min__;
    LandmarkFinderConfig __default__;
    dynamic_reconfigure::ConfigDescription __description_message__;

    static const LandmarkFinderConfigStatics *get_instance()
    {
      // Split this off in a separate function because I know that
      // instance will get initialized the first time get_instance is
      // called, and I am guaranteeing that get_instance gets called at
      // most once.
      static LandmarkFinderConfigStatics instance;
      return &instance;
    }
  };

  inline const dynamic_reconfigure::ConfigDescription &LandmarkFinderConfig::__getDescriptionMessage__()
  {
    return __get_statics__()->__description_message__;
  }

  inline const LandmarkFinderConfig &LandmarkFinderConfig::__getDefault__()
  {
    return __get_statics__()->__default__;
  }

  inline const LandmarkFinderConfig &LandmarkFinderConfig::__getMax__()
  {
    return __get_statics__()->__max__;
  }

  inline const LandmarkFinderConfig &LandmarkFinderConfig::__getMin__()
  {
    return __get_statics__()->__min__;
  }

  inline const std::vector<LandmarkFinderConfig::AbstractParamDescriptionConstPtr> &LandmarkFinderConfig::__getParamDescriptions__()
  {
    return __get_statics__()->__param_descriptions__;
  }

  inline const std::vector<LandmarkFinderConfig::AbstractGroupDescriptionConstPtr> &LandmarkFinderConfig::__getGroupDescriptions__()
  {
    return __get_statics__()->__group_descriptions__;
  }

  inline const LandmarkFinderConfigStatics *LandmarkFinderConfig::__get_statics__()
  {
    const static LandmarkFinderConfigStatics *statics;

    if (statics) // Common case
      return statics;

    boost::mutex::scoped_lock lock(dynamic_reconfigure::__init_mutex__);

    if (statics) // In case we lost a race.
      return statics;

    statics = LandmarkFinderConfigStatics::get_instance();

    return statics;
  }


}

#endif // __LANDMARKFINDERRECONFIGURATOR_H__
