set(_CATKIN_CURRENT_PACKAGE "vehicle_setup")
set(vehicle_setup_VERSION "0.0.0")
set(vehicle_setup_MAINTAINER "wechtc@gmail.com <wechtc@gmail.com>")
set(vehicle_setup_PACKAGE_FORMAT "2")
set(vehicle_setup_BUILD_DEPENDS "mrt_cmake_modules" "prosilica_driver" "stargazer_ros_tool" "robot_state_publisher" "tf2_ros" "stereo_image_proc" "image_view" "hector_trajectory_server" "image_preproc_ros_tool")
set(vehicle_setup_BUILD_EXPORT_DEPENDS "prosilica_driver" "stargazer_ros_tool" "robot_state_publisher" "tf2_ros" "stereo_image_proc" "image_view" "hector_trajectory_server" "image_preproc_ros_tool")
set(vehicle_setup_BUILDTOOL_DEPENDS "catkin")
set(vehicle_setup_BUILDTOOL_EXPORT_DEPENDS )
set(vehicle_setup_EXEC_DEPENDS "prosilica_driver" "stargazer_ros_tool" "robot_state_publisher" "tf2_ros" "stereo_image_proc" "image_view" "hector_trajectory_server" "image_preproc_ros_tool")
set(vehicle_setup_RUN_DEPENDS "prosilica_driver" "stargazer_ros_tool" "robot_state_publisher" "tf2_ros" "stereo_image_proc" "image_view" "hector_trajectory_server" "image_preproc_ros_tool")
set(vehicle_setup_TEST_DEPENDS "gtest")
set(vehicle_setup_DOC_DEPENDS )
set(vehicle_setup_URL_WEBSITE "")
set(vehicle_setup_URL_BUGTRACKER "")
set(vehicle_setup_URL_REPOSITORY "git@gitlab.mrt.uni-karlsruhe.de:kognitive_automobile_labor/vehicle_setup.git")
set(vehicle_setup_DEPRECATED "")