set(_CATKIN_CURRENT_PACKAGE "stargazer_ros_tool")
set(stargazer_ros_tool_VERSION "0.0.0")
set(stargazer_ros_tool_MAINTAINER "Sascha Wirges <wirges@fzi.de>")
set(stargazer_ros_tool_PACKAGE_FORMAT "2")
set(stargazer_ros_tool_BUILD_DEPENDS "message_generation" "dynamic_reconfigure" "roscpp" "nodelet" "cv_bridge" "geometry_msgs" "image_transport" "message_filters" "mrt_ceres" "rosbag" "sensor_msgs" "stargazer" "std_msgs" "tf2_geometry_msgs" "tf2_ros" "visualization_msgs" "yaml-cpp")
set(stargazer_ros_tool_BUILD_EXPORT_DEPENDS "nodelet" "cv_bridge" "geometry_msgs" "image_transport" "message_filters" "mrt_ceres" "rosbag" "sensor_msgs" "stargazer" "std_msgs" "tf2_geometry_msgs" "tf2_ros" "visualization_msgs" "yaml-cpp")
set(stargazer_ros_tool_BUILDTOOL_DEPENDS "catkin")
set(stargazer_ros_tool_BUILDTOOL_EXPORT_DEPENDS )
set(stargazer_ros_tool_EXEC_DEPENDS "message_runtime" "nodelet" "cv_bridge" "geometry_msgs" "image_transport" "message_filters" "mrt_ceres" "rosbag" "sensor_msgs" "stargazer" "std_msgs" "tf2_geometry_msgs" "tf2_ros" "visualization_msgs" "yaml-cpp")
set(stargazer_ros_tool_RUN_DEPENDS "message_runtime" "nodelet" "cv_bridge" "geometry_msgs" "image_transport" "message_filters" "mrt_ceres" "rosbag" "sensor_msgs" "stargazer" "std_msgs" "tf2_geometry_msgs" "tf2_ros" "visualization_msgs" "yaml-cpp")
set(stargazer_ros_tool_TEST_DEPENDS "gtest")
set(stargazer_ros_tool_DOC_DEPENDS )
set(stargazer_ros_tool_URL_WEBSITE "")
set(stargazer_ros_tool_URL_BUGTRACKER "")
set(stargazer_ros_tool_URL_REPOSITORY "https://gitlab.mrt.uni-karlsruhe.de/MRT/stargazer_ros_tool.git")
set(stargazer_ros_tool_DEPRECATED "")