// Generated by gencpp from file traffic_sign_detection_ros_tool/jihuo.msg
// DO NOT EDIT!


#ifndef TRAFFIC_SIGN_DETECTION_ROS_TOOL_MESSAGE_JIHUO_H
#define TRAFFIC_SIGN_DETECTION_ROS_TOOL_MESSAGE_JIHUO_H

#include <ros/service_traits.h>


#include <traffic_sign_detection_ros_tool/jihuoRequest.h>
#include <traffic_sign_detection_ros_tool/jihuoResponse.h>


namespace traffic_sign_detection_ros_tool
{

struct jihuo
{

typedef jihuoRequest Request;
typedef jihuoResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct jihuo
} // namespace traffic_sign_detection_ros_tool


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::traffic_sign_detection_ros_tool::jihuo > {
  static const char* value()
  {
    return "226ee36d4761e1eb439a49b241f4bd84";
  }

  static const char* value(const ::traffic_sign_detection_ros_tool::jihuo&) { return value(); }
};

template<>
struct DataType< ::traffic_sign_detection_ros_tool::jihuo > {
  static const char* value()
  {
    return "traffic_sign_detection_ros_tool/jihuo";
  }

  static const char* value(const ::traffic_sign_detection_ros_tool::jihuo&) { return value(); }
};


// service_traits::MD5Sum< ::traffic_sign_detection_ros_tool::jihuoRequest> should match 
// service_traits::MD5Sum< ::traffic_sign_detection_ros_tool::jihuo > 
template<>
struct MD5Sum< ::traffic_sign_detection_ros_tool::jihuoRequest>
{
  static const char* value()
  {
    return MD5Sum< ::traffic_sign_detection_ros_tool::jihuo >::value();
  }
  static const char* value(const ::traffic_sign_detection_ros_tool::jihuoRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::traffic_sign_detection_ros_tool::jihuoRequest> should match 
// service_traits::DataType< ::traffic_sign_detection_ros_tool::jihuo > 
template<>
struct DataType< ::traffic_sign_detection_ros_tool::jihuoRequest>
{
  static const char* value()
  {
    return DataType< ::traffic_sign_detection_ros_tool::jihuo >::value();
  }
  static const char* value(const ::traffic_sign_detection_ros_tool::jihuoRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::traffic_sign_detection_ros_tool::jihuoResponse> should match 
// service_traits::MD5Sum< ::traffic_sign_detection_ros_tool::jihuo > 
template<>
struct MD5Sum< ::traffic_sign_detection_ros_tool::jihuoResponse>
{
  static const char* value()
  {
    return MD5Sum< ::traffic_sign_detection_ros_tool::jihuo >::value();
  }
  static const char* value(const ::traffic_sign_detection_ros_tool::jihuoResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::traffic_sign_detection_ros_tool::jihuoResponse> should match 
// service_traits::DataType< ::traffic_sign_detection_ros_tool::jihuo > 
template<>
struct DataType< ::traffic_sign_detection_ros_tool::jihuoResponse>
{
  static const char* value()
  {
    return DataType< ::traffic_sign_detection_ros_tool::jihuo >::value();
  }
  static const char* value(const ::traffic_sign_detection_ros_tool::jihuoResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TRAFFIC_SIGN_DETECTION_ROS_TOOL_MESSAGE_JIHUO_H
