// Generated by gencpp from file motor_interface_ros_tool/Activation.msg
// DO NOT EDIT!


#ifndef MOTOR_INTERFACE_ROS_TOOL_MESSAGE_ACTIVATION_H
#define MOTOR_INTERFACE_ROS_TOOL_MESSAGE_ACTIVATION_H

#include <ros/service_traits.h>


#include <motor_interface_ros_tool/ActivationRequest.h>
#include <motor_interface_ros_tool/ActivationResponse.h>


namespace motor_interface_ros_tool
{

struct Activation
{

typedef ActivationRequest Request;
typedef ActivationResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Activation
} // namespace motor_interface_ros_tool


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::motor_interface_ros_tool::Activation > {
  static const char* value()
  {
    return "b15627a984ebdd591b2ee87ce75c4d06";
  }

  static const char* value(const ::motor_interface_ros_tool::Activation&) { return value(); }
};

template<>
struct DataType< ::motor_interface_ros_tool::Activation > {
  static const char* value()
  {
    return "motor_interface_ros_tool/Activation";
  }

  static const char* value(const ::motor_interface_ros_tool::Activation&) { return value(); }
};


// service_traits::MD5Sum< ::motor_interface_ros_tool::ActivationRequest> should match 
// service_traits::MD5Sum< ::motor_interface_ros_tool::Activation > 
template<>
struct MD5Sum< ::motor_interface_ros_tool::ActivationRequest>
{
  static const char* value()
  {
    return MD5Sum< ::motor_interface_ros_tool::Activation >::value();
  }
  static const char* value(const ::motor_interface_ros_tool::ActivationRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::motor_interface_ros_tool::ActivationRequest> should match 
// service_traits::DataType< ::motor_interface_ros_tool::Activation > 
template<>
struct DataType< ::motor_interface_ros_tool::ActivationRequest>
{
  static const char* value()
  {
    return DataType< ::motor_interface_ros_tool::Activation >::value();
  }
  static const char* value(const ::motor_interface_ros_tool::ActivationRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::motor_interface_ros_tool::ActivationResponse> should match 
// service_traits::MD5Sum< ::motor_interface_ros_tool::Activation > 
template<>
struct MD5Sum< ::motor_interface_ros_tool::ActivationResponse>
{
  static const char* value()
  {
    return MD5Sum< ::motor_interface_ros_tool::Activation >::value();
  }
  static const char* value(const ::motor_interface_ros_tool::ActivationResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::motor_interface_ros_tool::ActivationResponse> should match 
// service_traits::DataType< ::motor_interface_ros_tool::Activation > 
template<>
struct DataType< ::motor_interface_ros_tool::ActivationResponse>
{
  static const char* value()
  {
    return DataType< ::motor_interface_ros_tool::Activation >::value();
  }
  static const char* value(const ::motor_interface_ros_tool::ActivationResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MOTOR_INTERFACE_ROS_TOOL_MESSAGE_ACTIVATION_H
