# CMake generated Testfile for 
# Source directory: /home/kal5-1/cargogo/src/vision_opencv/cv_bridge/test
# Build directory: /home/kal5-1/cargogo/build_debug/cv_bridge/test
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(_ctest_cv_bridge_gtest_cv_bridge-utest "/home/kal5-1/cargogo/build_debug/cv_bridge/catkin_generated/env_cached.sh" "/opt/mrtsoftware/release/lib/mrt-build-tools/bin/python" "/opt/ros/kinetic/share/catkin/cmake/test/run_tests.py" "/home/kal5-1/cargogo/build_debug/cv_bridge/test_results/cv_bridge/gtest-cv_bridge-utest.xml" "--return-code" "/home/kal5-1/cargogo/devel_debug/.private/cv_bridge/lib/cv_bridge/cv_bridge-utest --gtest_output=xml:/home/kal5-1/cargogo/build_debug/cv_bridge/test_results/cv_bridge/gtest-cv_bridge-utest.xml")
add_test(_ctest_cv_bridge_nosetests_enumerants.py "/home/kal5-1/cargogo/build_debug/cv_bridge/catkin_generated/env_cached.sh" "/opt/mrtsoftware/release/lib/mrt-build-tools/bin/python" "/opt/ros/kinetic/share/catkin/cmake/test/run_tests.py" "/home/kal5-1/cargogo/build_debug/cv_bridge/test_results/cv_bridge/nosetests-enumerants.py.xml" "--return-code" "/usr/bin/cmake -E make_directory /home/kal5-1/cargogo/build_debug/cv_bridge/test_results/cv_bridge" "/usr/bin/nosetests-2.7 -P --process-timeout=60 /home/kal5-1/cargogo/src/vision_opencv/cv_bridge/test/enumerants.py --with-xunit --xunit-file=/home/kal5-1/cargogo/build_debug/cv_bridge/test_results/cv_bridge/nosetests-enumerants.py.xml")
add_test(_ctest_cv_bridge_nosetests_conversions.py "/home/kal5-1/cargogo/build_debug/cv_bridge/catkin_generated/env_cached.sh" "/opt/mrtsoftware/release/lib/mrt-build-tools/bin/python" "/opt/ros/kinetic/share/catkin/cmake/test/run_tests.py" "/home/kal5-1/cargogo/build_debug/cv_bridge/test_results/cv_bridge/nosetests-conversions.py.xml" "--return-code" "/usr/bin/cmake -E make_directory /home/kal5-1/cargogo/build_debug/cv_bridge/test_results/cv_bridge" "/usr/bin/nosetests-2.7 -P --process-timeout=60 /home/kal5-1/cargogo/src/vision_opencv/cv_bridge/test/conversions.py --with-xunit --xunit-file=/home/kal5-1/cargogo/build_debug/cv_bridge/test_results/cv_bridge/nosetests-conversions.py.xml")
add_test(_ctest_cv_bridge_nosetests_python_bindings.py "/home/kal5-1/cargogo/build_debug/cv_bridge/catkin_generated/env_cached.sh" "/opt/mrtsoftware/release/lib/mrt-build-tools/bin/python" "/opt/ros/kinetic/share/catkin/cmake/test/run_tests.py" "/home/kal5-1/cargogo/build_debug/cv_bridge/test_results/cv_bridge/nosetests-python_bindings.py.xml" "--return-code" "/usr/bin/cmake -E make_directory /home/kal5-1/cargogo/build_debug/cv_bridge/test_results/cv_bridge" "/usr/bin/nosetests-2.7 -P --process-timeout=60 /home/kal5-1/cargogo/src/vision_opencv/cv_bridge/test/python_bindings.py --with-xunit --xunit-file=/home/kal5-1/cargogo/build_debug/cv_bridge/test_results/cv_bridge/nosetests-python_bindings.py.xml")
