// *********************************************************
//
// File autogenerated for the path_provider_ros_tool package
// by the rosparam_handler package.
// Please do not edit.
//
// ********************************************************/

#pragma once

#include <stdlib.h>
#include <string>
#include <limits>
#include <ros/param.h>
#include <ros/node_handle.h>
#ifdef DYNAMIC_RECONFIGURE_FOUND
#include <path_provider_ros_tool/PathProviderConfig.h>
#else
struct PathProviderConfig{};
#endif


namespace path_provider_ros_tool {

inline std::string getNodeName(const ros::NodeHandle& privateNodeHandle){
    std::string name_space = privateNodeHandle.getNamespace();
    std::stringstream tempString(name_space);
    std::string name;
    while(std::getline(tempString, name, '/')){;}
    return name;
}

template <typename T>
std::ostream& operator<< (std::ostream& out, const std::vector<T>& v) {
  if ( !v.empty() ) {
    out << '[';
    std::copy (v.begin(), v.end(), std::ostream_iterator<T>(out, ", "));
    out << "\b\b]";
  }
  return out;
}

template<typename T1, typename T2>
std::ostream &operator<<(std::ostream &stream, const std::map<T1, T2>& map)
{
  stream << '{';
  for (typename std::map<T1, T2>::const_iterator it = map.begin();
       it != map.end();
       ++it)
    {
      stream << (*it).first << " --> " << (*it).second << ", ";
    }
  stream << '}';
  return stream;
}

struct PathProviderParameters {

  using Config = PathProviderConfig;

  PathProviderParameters(const ros::NodeHandle& private_node_handle)
  : globalNamespace{"/"},
    privateNamespace{private_node_handle.getNamespace() + "/"},
    nodeName{getNodeName(private_node_handle)} {}

  void fromParamServer(){
    getParam(privateNamespace + "msg_queue_size", msg_queue_size, int{5});
    getParam(privateNamespace + "verbosity", verbosity, std::string{"info"});
    getParam(privateNamespace + "topic_publisher", topic_publisher, std::string{"/path"});
    getParam(privateNamespace + "dipatcher_rate", dipatcher_rate, double{10});
    getParam(privateNamespace + "timer_rate", timer_rate, double{2});
    getParam(privateNamespace + "frame_id_map", frame_id_map, std::string{"map"});
    getParam(privateNamespace + "frame_id_vehicle", frame_id_vehicle, std::string{"vehicle"});
    getParam(privateNamespace + "frame_id_camera", frame_id_camera, std::string{"camera_top"});
    getParam(privateNamespace + "frame_id_stargazer", frame_id_stargazer, std::string{"stargazer"});

    testMin<int>(privateNamespace + "msg_queue_size", msg_queue_size, 1);
    testMin<double>(privateNamespace + "dipatcher_rate", dipatcher_rate, 1);
    testMax<double>(privateNamespace + "dipatcher_rate", dipatcher_rate, 20);
    testMin<double>(privateNamespace + "timer_rate", timer_rate, 1);
    testMax<double>(privateNamespace + "timer_rate", timer_rate, 20);
  ROS_DEBUG_STREAM(*this);
  }

  void fromConfig(const Config& config, const uint32_t level = 0){
#ifdef DYNAMIC_RECONFIGURE_FOUND
    dipatcher_rate = config.dipatcher_rate;
    timer_rate = config.timer_rate;
#else
  ROS_FATAL_STREAM("dynamic_reconfigure was not found during compilation. So fromConfig() is not available. Please recompile with dynamic_reconfigure.");
  std::exit(EXIT_FAILURE);
#endif
  }

  friend std::ostream& operator<<(std::ostream& os, const PathProviderParameters& p)
  {
    os << "[" << p.nodeName << "]\nNode " << p.nodeName << " has the following parameters:\n"
      << "	" << p.privateNamespace << "msg_queue_size:" << p.msg_queue_size << "\n"
      << "	" << p.privateNamespace << "verbosity:" << p.verbosity << "\n"
      << "	" << p.privateNamespace << "topic_publisher:" << p.topic_publisher << "\n"
      << "	" << p.privateNamespace << "dipatcher_rate:" << p.dipatcher_rate << "\n"
      << "	" << p.privateNamespace << "timer_rate:" << p.timer_rate << "\n"
      << "	" << p.privateNamespace << "frame_id_map:" << p.frame_id_map << "\n"
      << "	" << p.privateNamespace << "frame_id_vehicle:" << p.frame_id_vehicle << "\n"
      << "	" << p.privateNamespace << "frame_id_camera:" << p.frame_id_camera << "\n"
      << "	" << p.privateNamespace << "frame_id_stargazer:" << p.frame_id_stargazer << "\n"
;
    return os;
  }

  void missingParamsWarning(){
    ROS_WARN_STREAM("[" << nodeName << "]\nThe following parameters do not have default values and need to be specified:\n"
    );
  }

  template <typename T>
  void getParam(const std::string key, T& val) {
    if (!ros::param::has(key)) {
      ROS_ERROR_STREAM("Parameter '" << key << "' is not defined.");
      missingParamsWarning();
      std::exit(EXIT_FAILURE);
    } else if (!ros::param::get(key, val)) {
      ROS_ERROR_STREAM("Could not retrieve parameter'" << key << "'. Does it have a different type?");
      missingParamsWarning();
      std::exit(EXIT_FAILURE);
    }
  }

  template <typename T>
  void getParam(const std::string key, T& val, const T& defaultValue) {
    if (!ros::param::has(key)) {
        val = defaultValue;
        ros::param::set(key, defaultValue);
        ROS_INFO_STREAM("Parameter "<<key<<" is not yet set. Setting default value.");
    } else if (!ros::param::get(key, val)) {
        ROS_WARN_STREAM("Parameter "<<key<<" is set, but has a different type. Using default value instead.");
        val = defaultValue;
	}
  }

  void testConstParam(const std::string key){
    if (ros::param::has(key)) {
      ROS_WARN_STREAM("Parameter " << key << "' was set on the parameter server eventhough it was defined to be constant.");
    }
  }

  template<typename T>
  void testMin(const std::string key, T& val, T min = std::numeric_limits<T>::min()){
    if (val < min){
      ROS_WARN_STREAM("Value of " << val << " for " << key << " is smaller than minimal allowed value. Correcting value to min=" << min);
      val = min;
    }
  }

  template<typename T>
  void testMax(const std::string key, T& val, T max = std::numeric_limits<T>::max()){
    if (val > max){
      ROS_WARN_STREAM("Value of " << val << " for " << key << " is greater than maximal allowed. Correcting value to max=" << max);
      val = max;
    }
  }

    int msg_queue_size; /*!< Queusize for publisher */
  std::string verbosity; /*!< Set logger level for this node */
  std::string topic_publisher; /*!< Topic name of publisher */
  double dipatcher_rate; /*!< dipatcher rate in Hz */
  double timer_rate; /*!< Timer rate in Hz */
  std::string frame_id_map; /*!< Map frame ID */
  std::string frame_id_vehicle; /*!< Vehicle frame ID */
  std::string frame_id_camera; /*!< Top camera frame ID */
  std::string frame_id_stargazer; /*!< Stargazer frame ID */

  private:
    const std::string globalNamespace;
    const std::string privateNamespace;
    const std::string nodeName;
};

} // namespace path_provider_ros_tool
