set(_CATKIN_CURRENT_PACKAGE "joy_converter_ros_tool")
set(joy_converter_ros_tool_VERSION "0.0.0")
set(joy_converter_ros_tool_MAINTAINER "wechtc@gmail.com <wechtc@gmail.com>")
set(joy_converter_ros_tool_PACKAGE_FORMAT "2")
set(joy_converter_ros_tool_BUILD_DEPENDS "mrt_cmake_modules" "message_generation" "roscpp" "roslib" "utils_ros" "motor_interface_ros_tool" "joy")
set(joy_converter_ros_tool_BUILD_EXPORT_DEPENDS "roslib" "utils_ros" "motor_interface_ros_tool" "joy")
set(joy_converter_ros_tool_BUILDTOOL_DEPENDS "catkin")
set(joy_converter_ros_tool_BUILDTOOL_EXPORT_DEPENDS )
set(joy_converter_ros_tool_EXEC_DEPENDS "message_runtime" "roslib" "utils_ros" "motor_interface_ros_tool" "joy")
set(joy_converter_ros_tool_RUN_DEPENDS "message_runtime" "roslib" "utils_ros" "motor_interface_ros_tool" "joy")
set(joy_converter_ros_tool_TEST_DEPENDS "gtest")
set(joy_converter_ros_tool_DOC_DEPENDS )
set(joy_converter_ros_tool_URL_WEBSITE "")
set(joy_converter_ros_tool_URL_BUGTRACKER "")
set(joy_converter_ros_tool_URL_REPOSITORY "git@gitlab.mrt.uni-karlsruhe.de:kognitive_automobile_labor/joy_converter_ros_tool.git")
set(joy_converter_ros_tool_DEPRECATED "")