set(_CATKIN_CURRENT_PACKAGE "simulation_ros_tool")
set(simulation_ros_tool_VERSION "0.0.0")
set(simulation_ros_tool_MAINTAINER "wechtc@gmail.com <wechtc@gmail.com>")
set(simulation_ros_tool_PACKAGE_FORMAT "2")
set(simulation_ros_tool_BUILD_DEPENDS "mrt_cmake_modules" "rosparam_handler" "message_generation" "roscpp" "roslib" "nodelet" "utils_ros" "dynamic_reconfigure" "tf2_ros" "motor_interface_ros_tool" "eigen" "tf2_eigen")
set(simulation_ros_tool_BUILD_EXPORT_DEPENDS "roslib" "nodelet" "utils_ros" "dynamic_reconfigure" "tf2_ros" "motor_interface_ros_tool" "eigen" "tf2_eigen")
set(simulation_ros_tool_BUILDTOOL_DEPENDS "catkin")
set(simulation_ros_tool_BUILDTOOL_EXPORT_DEPENDS )
set(simulation_ros_tool_EXEC_DEPENDS "message_runtime" "roslib" "nodelet" "utils_ros" "dynamic_reconfigure" "tf2_ros" "motor_interface_ros_tool" "eigen" "tf2_eigen")
set(simulation_ros_tool_RUN_DEPENDS "message_runtime" "roslib" "nodelet" "utils_ros" "dynamic_reconfigure" "tf2_ros" "motor_interface_ros_tool" "eigen" "tf2_eigen")
set(simulation_ros_tool_TEST_DEPENDS "gtest" "rostest")
set(simulation_ros_tool_DOC_DEPENDS )
set(simulation_ros_tool_URL_WEBSITE "")
set(simulation_ros_tool_URL_BUGTRACKER "")
set(simulation_ros_tool_URL_REPOSITORY "git@gitlab.mrt.uni-karlsruhe.de:kognitive_automobile_labor/simulation_ros_tool.git")
set(simulation_ros_tool_DEPRECATED "")