set(_CATKIN_CURRENT_PACKAGE "motor_interface")
set(motor_interface_VERSION "0.0.0")
set(motor_interface_MAINTAINER "wechtc@gmail.com <wechtc@gmail.com>")
set(motor_interface_PACKAGE_FORMAT "2")
set(motor_interface_BUILD_DEPENDS "iowkit")
set(motor_interface_BUILD_EXPORT_DEPENDS "iowkit")
set(motor_interface_BUILDTOOL_DEPENDS "catkin")
set(motor_interface_BUILDTOOL_EXPORT_DEPENDS )
set(motor_interface_EXEC_DEPENDS "iowkit")
set(motor_interface_RUN_DEPENDS "iowkit")
set(motor_interface_TEST_DEPENDS "gtest")
set(motor_interface_DOC_DEPENDS )
set(motor_interface_URL_WEBSITE "")
set(motor_interface_URL_BUGTRACKER "")
set(motor_interface_URL_REPOSITORY "git@gitlab.mrt.uni-karlsruhe.de:kognitive_automobile_labor/motor_interface.git")
set(motor_interface_DEPRECATED "")