// Generated by gencpp from file motor_interface_ros_tool/ActivationResponse.msg
// DO NOT EDIT!


#ifndef MOTOR_INTERFACE_ROS_TOOL_MESSAGE_ACTIVATIONRESPONSE_H
#define MOTOR_INTERFACE_ROS_TOOL_MESSAGE_ACTIVATIONRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace motor_interface_ros_tool
{
template <class ContainerAllocator>
struct ActivationResponse_
{
  typedef ActivationResponse_<ContainerAllocator> Type;

  ActivationResponse_()
    {
    }
  ActivationResponse_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::motor_interface_ros_tool::ActivationResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::motor_interface_ros_tool::ActivationResponse_<ContainerAllocator> const> ConstPtr;

}; // struct ActivationResponse_

typedef ::motor_interface_ros_tool::ActivationResponse_<std::allocator<void> > ActivationResponse;

typedef boost::shared_ptr< ::motor_interface_ros_tool::ActivationResponse > ActivationResponsePtr;
typedef boost::shared_ptr< ::motor_interface_ros_tool::ActivationResponse const> ActivationResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::motor_interface_ros_tool::ActivationResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::motor_interface_ros_tool::ActivationResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace motor_interface_ros_tool

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'motor_interface_ros_tool': ['/home/kal5-1/cargogo/src/motor_interface_ros_tool/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::motor_interface_ros_tool::ActivationResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::motor_interface_ros_tool::ActivationResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::motor_interface_ros_tool::ActivationResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::motor_interface_ros_tool::ActivationResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::motor_interface_ros_tool::ActivationResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::motor_interface_ros_tool::ActivationResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::motor_interface_ros_tool::ActivationResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::motor_interface_ros_tool::ActivationResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::motor_interface_ros_tool::ActivationResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "motor_interface_ros_tool/ActivationResponse";
  }

  static const char* value(const ::motor_interface_ros_tool::ActivationResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::motor_interface_ros_tool::ActivationResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n\
";
  }

  static const char* value(const ::motor_interface_ros_tool::ActivationResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::motor_interface_ros_tool::ActivationResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ActivationResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::motor_interface_ros_tool::ActivationResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::motor_interface_ros_tool::ActivationResponse_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // MOTOR_INTERFACE_ROS_TOOL_MESSAGE_ACTIVATIONRESPONSE_H
