// Generated by gencpp from file motor_interface_ros_tool/MotorCommand.msg
// DO NOT EDIT!


#ifndef MOTOR_INTERFACE_ROS_TOOL_MESSAGE_MOTORCOMMAND_H
#define MOTOR_INTERFACE_ROS_TOOL_MESSAGE_MOTORCOMMAND_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace motor_interface_ros_tool
{
template <class ContainerAllocator>
struct MotorCommand_
{
  typedef MotorCommand_<ContainerAllocator> Type;

  MotorCommand_()
    : header()
    , velocity(0.0)  {
    }
  MotorCommand_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , velocity(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef float _velocity_type;
  _velocity_type velocity;





  typedef boost::shared_ptr< ::motor_interface_ros_tool::MotorCommand_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::motor_interface_ros_tool::MotorCommand_<ContainerAllocator> const> ConstPtr;

}; // struct MotorCommand_

typedef ::motor_interface_ros_tool::MotorCommand_<std::allocator<void> > MotorCommand;

typedef boost::shared_ptr< ::motor_interface_ros_tool::MotorCommand > MotorCommandPtr;
typedef boost::shared_ptr< ::motor_interface_ros_tool::MotorCommand const> MotorCommandConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::motor_interface_ros_tool::MotorCommand_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::motor_interface_ros_tool::MotorCommand_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace motor_interface_ros_tool

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'motor_interface_ros_tool': ['/home/kal5-1/cargogo/src/motor_interface_ros_tool/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::motor_interface_ros_tool::MotorCommand_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::motor_interface_ros_tool::MotorCommand_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::motor_interface_ros_tool::MotorCommand_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::motor_interface_ros_tool::MotorCommand_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::motor_interface_ros_tool::MotorCommand_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::motor_interface_ros_tool::MotorCommand_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::motor_interface_ros_tool::MotorCommand_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f829323f183fabb3f889a576f21902c2";
  }

  static const char* value(const ::motor_interface_ros_tool::MotorCommand_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf829323f183fabb3ULL;
  static const uint64_t static_value2 = 0xf889a576f21902c2ULL;
};

template<class ContainerAllocator>
struct DataType< ::motor_interface_ros_tool::MotorCommand_<ContainerAllocator> >
{
  static const char* value()
  {
    return "motor_interface_ros_tool/MotorCommand";
  }

  static const char* value(const ::motor_interface_ros_tool::MotorCommand_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::motor_interface_ros_tool::MotorCommand_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
\n\
float32 velocity       # the velocity of the car in [m/s]\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::motor_interface_ros_tool::MotorCommand_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::motor_interface_ros_tool::MotorCommand_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.velocity);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MotorCommand_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::motor_interface_ros_tool::MotorCommand_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::motor_interface_ros_tool::MotorCommand_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "velocity: ";
    Printer<float>::stream(s, indent + "  ", v.velocity);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MOTOR_INTERFACE_ROS_TOOL_MESSAGE_MOTORCOMMAND_H
